// Instrument type definitions separated from factory for better organization

import type { InstrumentTypeInfo } from '../../types/instruments'
import { InstrumentType, ParameterType } from '../../types/instruments'

export const INSTRUMENT_TYPE_DEFINITIONS: InstrumentTypeInfo[] = [
  {
    type: 'polySynth',
    name: 'Polyphonic Synthesizer',
    description: 'Multi-voice synthesizer capable of playing chords',
    category: InstrumentType.SYNTH,
    supportsPolyphony: true,
    supportsSustain: true,
    parameterDefinitions: [
      {
        id: 'oscillatorType',
        name: 'Oscillator Type',
        type: ParameterType.SELECT,
        defaultValue: 'sine',
        options: ['sine', 'square', 'sawtooth', 'triangle'],
        description: 'Basic waveform type',
      },
      {
        id: 'attack',
        name: 'Attack',
        type: ParameterType.RANGE,
        defaultValue: 0.1,
        min: 0.001,
        max: 2,
        step: 0.001,
        unit: 's',
        description: 'Envelope attack time',
      },
      {
        id: 'decay',
        name: 'Decay',
        type: ParameterType.RANGE,
        defaultValue: 0.3,
        min: 0.001,
        max: 2,
        step: 0.001,
        unit: 's',
        description: 'Envelope decay time',
      },
      {
        id: 'sustain',
        name: 'Sustain',
        type: ParameterType.RANGE,
        defaultValue: 0.6,
        min: 0,
        max: 1,
        step: 0.01,
        description: 'Envelope sustain level',
      },
      {
        id: 'release',
        name: 'Release',
        type: ParameterType.RANGE,
        defaultValue: 0.8,
        min: 0.001,
        max: 5,
        step: 0.001,
        unit: 's',
        description: 'Envelope release time',
      },
      {
        id: 'filterFrequency',
        name: 'Filter Frequency',
        type: ParameterType.RANGE,
        defaultValue: 1000,
        min: 20,
        max: 20000,
        step: 1,
        unit: 'Hz',
        description: 'Filter cutoff frequency',
      },
      {
        id: 'filterResonance',
        name: 'Filter Resonance',
        type: ParameterType.RANGE,
        defaultValue: 1,
        min: 0.1,
        max: 30,
        step: 0.1,
        description: 'Filter resonance (Q factor)',
      },
    ],
  },
  {
    type: 'monoSynth',
    name: 'Monophonic Synthesizer',
    description: 'Single-voice synthesizer for leads and bass',
    category: InstrumentType.SYNTH,
    supportsPolyphony: false,
    supportsSustain: true,
    parameterDefinitions: [
      {
        id: 'oscillatorType',
        name: 'Oscillator Type',
        type: ParameterType.SELECT,
        defaultValue: 'sawtooth',
        options: ['sine', 'square', 'sawtooth', 'triangle'],
        description: 'Basic waveform type',
      },
      {
        id: 'attack',
        name: 'Attack',
        type: ParameterType.RANGE,
        defaultValue: 0.01,
        min: 0.001,
        max: 1,
        step: 0.001,
        unit: 's',
        description: 'Envelope attack time',
      },
      {
        id: 'decay',
        name: 'Decay',
        type: ParameterType.RANGE,
        defaultValue: 0.1,
        min: 0.001,
        max: 2,
        step: 0.001,
        unit: 's',
        description: 'Envelope decay time',
      },
      {
        id: 'sustain',
        name: 'Sustain',
        type: ParameterType.RANGE,
        defaultValue: 0.8,
        min: 0,
        max: 1,
        step: 0.01,
        description: 'Envelope sustain level',
      },
      {
        id: 'release',
        name: 'Release',
        type: ParameterType.RANGE,
        defaultValue: 0.3,
        min: 0.001,
        max: 5,
        step: 0.001,
        unit: 's',
        description: 'Envelope release time',
      },
      {
        id: 'portamento',
        name: 'Portamento',
        type: ParameterType.RANGE,
        defaultValue: 0,
        min: 0,
        max: 1,
        step: 0.01,
        unit: 's',
        description: 'Glide time between notes',
      },
    ],
  },
  {
    type: 'drumKit',
    name: 'Drum Kit',
    description: 'Multi-sample drum kit with multiple voices',
    category: InstrumentType.DRUM,
    supportsPolyphony: true,
    supportsSustain: false,
    parameterDefinitions: [
      {
        id: 'kitType',
        name: 'Kit Type',
        type: ParameterType.SELECT,
        defaultValue: '808',
        options: ['808', '909', 'acoustic', 'electronic'],
        description: 'Drum kit character',
      },
      {
        id: 'kickTune',
        name: 'Kick Tune',
        type: ParameterType.RANGE,
        defaultValue: 0,
        min: -12,
        max: 12,
        step: 0.1,
        unit: 'st',
        description: 'Kick drum tuning',
      },
      {
        id: 'snareTune',
        name: 'Snare Tune',
        type: ParameterType.RANGE,
        defaultValue: 0,
        min: -12,
        max: 12,
        step: 0.1,
        unit: 'st',
        description: 'Snare drum tuning',
      },
      {
        id: 'hihatDecay',
        name: 'Hi-hat Decay',
        type: ParameterType.RANGE,
        defaultValue: 0.1,
        min: 0.01,
        max: 1,
        step: 0.01,
        unit: 's',
        description: 'Hi-hat decay time',
      },
    ],
  },
]
